// Pure rules for product images held in Supabase Storage. Free of database,
// network, and server-only imports so the same checks can back a future upload
// action, the admin data layer, and their tests.
//
// Nothing here uploads, deletes, or reads anything. It decides what a file is
// from its own bytes, where it would be stored, and whether a given URL is one
// of ours.
//
// The rules for images that live as local paths under public/ are unchanged and
// stay in product-image-rules.ts. The two coexist: image_url holds whichever
// form an image uses, and only Storage-backed rows also carry an object path.

export const PRODUCT_IMAGE_BUCKET = "product-images";

/**
 * 4 MiB, matching the bucket's own file_size_limit.
 *
 * The ceiling is a platform constraint as much as a preference: an upload
 * travels through a server function, and Vercel caps a serverless request body
 * at roughly 4.5 MB. Existing product photographs are 121–148 KB, so this
 * leaves generous headroom while staying under that limit.
 */
export const MAX_PRODUCT_IMAGE_BYTES = 4 * 1024 * 1024;

export const ALLOWED_PRODUCT_IMAGE_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
] as const;

export type ProductImageMimeType =
  (typeof ALLOWED_PRODUCT_IMAGE_MIME_TYPES)[number];

/**
 * The extension each accepted type is stored with.
 *
 * Derived from the type detected in the file's own bytes, never from the name
 * the browser supplied, so a file called `photo.jpg` that actually contains PNG
 * bytes is stored as `.png` — or, more usually, refused before it gets here.
 */
export const PRODUCT_IMAGE_EXTENSIONS: Record<ProductImageMimeType, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/avif": "avif",
};

const UUID_SOURCE =
  "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
const UUID_PATTERN = new RegExp(`^${UUID_SOURCE}$`, "i");

/**
 * Exactly the shape `buildProductImageObjectPath` produces: a product-scoped
 * folder, a random object name, and an accepted extension.
 *
 * Strict on purpose. Every object path this application stores is generated by
 * the builder below, so anything that does not match this shape is not one of
 * ours and must not be treated as one — which is what makes traversal, absolute
 * paths, and stray characters unreachable rather than merely filtered.
 */
const STORAGE_OBJECT_PATH_PATTERN = new RegExp(
  `^${UUID_SOURCE}/${UUID_SOURCE}\\.(?:${Object.values(
    PRODUCT_IMAGE_EXTENSIONS,
  ).join("|")})$`,
);

/** The public object endpoint for this bucket, and nothing else on the host. */
const STORAGE_PUBLIC_PREFIX = `/storage/v1/object/public/${PRODUCT_IMAGE_BUCKET}/`;

// Magic numbers. A browser-supplied MIME type and a filename extension are both
// trivially forged, so the bytes are the only thing consulted here.
const JPEG_SIGNATURE = [0xff, 0xd8, 0xff] as const;
const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] as const;
const RIFF_SIGNATURE = [0x52, 0x49, 0x46, 0x46] as const; // "RIFF"

// AVIF is ISO base media, so it is identified by its brands rather than a fixed
// prefix. Only these two are accepted: HEIC shares the same container and the
// same `ftyp` box but is not something next/image can render.
const AVIF_BRANDS = new Set(["avif", "avis"]);

function hasSignature(
  bytes: Uint8Array,
  signature: readonly number[],
  offset = 0,
): boolean {
  if (bytes.length < offset + signature.length) {
    return false;
  }

  return signature.every((byte, index) => bytes[offset + index] === byte);
}

/** Four-character box tags and brands are plain ASCII. */
function readAscii(bytes: Uint8Array, offset: number, length: number): string {
  if (bytes.length < offset + length) {
    return "";
  }

  let text = "";

  for (let index = 0; index < length; index += 1) {
    text += String.fromCharCode(bytes[offset + index]);
  }

  return text;
}

/** Big-endian, and multiplied rather than shifted to avoid a signed result. */
function readUint32(bytes: Uint8Array, offset: number): number {
  if (bytes.length < offset + 4) {
    return 0;
  }

  return (
    bytes[offset] * 2 ** 24 +
    bytes[offset + 1] * 2 ** 16 +
    bytes[offset + 2] * 2 ** 8 +
    bytes[offset + 3]
  );
}

function isWebp(bytes: Uint8Array): boolean {
  // "RIFF" then a four-byte length then "WEBP".
  return hasSignature(bytes, RIFF_SIGNATURE) && readAscii(bytes, 8, 4) === "WEBP";
}

function isAvif(bytes: Uint8Array): boolean {
  if (readAscii(bytes, 4, 4) !== "ftyp") {
    return false;
  }

  // The major brand sits right after the box tag.
  if (AVIF_BRANDS.has(readAscii(bytes, 8, 4))) {
    return true;
  }

  // Otherwise the file may declare a different major brand and list avif among
  // its compatible brands, which begin after the four-byte minor version.
  const boxEnd = Math.min(readUint32(bytes, 0), bytes.length);

  for (let offset = 16; offset + 4 <= boxEnd; offset += 4) {
    if (AVIF_BRANDS.has(readAscii(bytes, offset, 4))) {
      return true;
    }
  }

  return false;
}

/**
 * What a file actually is, read from its leading bytes, or null when it is not
 * one of the four accepted image formats.
 *
 * Only the first few dozen bytes are consulted, so a caller may pass a prefix
 * of the file rather than the whole thing.
 *
 * Everything else lands on null by construction, including the cases worth
 * naming: SVG is XML and matches no signature here; GIF is a real image format
 * but is not in the allowlist; a script, an archive, or a Mach-O or ELF binary
 * matches nothing; and a file named `.jpg` holding any of those is refused for
 * exactly the same reason.
 */
export function detectProductImageMimeType(
  bytes: Uint8Array,
): ProductImageMimeType | null {
  if (!(bytes instanceof Uint8Array) || bytes.length === 0) {
    return null;
  }

  if (hasSignature(bytes, JPEG_SIGNATURE)) {
    return "image/jpeg";
  }

  if (hasSignature(bytes, PNG_SIGNATURE)) {
    return "image/png";
  }

  if (isWebp(bytes)) {
    return "image/webp";
  }

  if (isAvif(bytes)) {
    return "image/avif";
  }

  return null;
}

export type ProductImageFileValidation =
  | { ok: true; mimeType: ProductImageMimeType; extension: string }
  | { ok: false; error: string };

/**
 * Whether a chosen file may be stored, and what it really is.
 *
 * Size is checked first because it is the cheaper question and because an
 * oversized file should be refused on its size rather than its contents. The
 * declared type a browser sends is deliberately never consulted: the detected
 * type is what the caller should record and send as the object's content type.
 */
export function validateProductImageFile(input: {
  size: number;
  bytes: Uint8Array;
}): ProductImageFileValidation {
  if (!Number.isFinite(input.size) || input.size <= 0) {
    return { ok: false, error: "That file is empty." };
  }

  if (input.size > MAX_PRODUCT_IMAGE_BYTES) {
    return {
      ok: false,
      error: `Images must be ${MAX_PRODUCT_IMAGE_BYTES / (1024 * 1024)} MB or smaller.`,
    };
  }

  const mimeType = detectProductImageMimeType(input.bytes);

  if (!mimeType) {
    return {
      ok: false,
      error: "That file is not a JPEG, PNG, WebP, or AVIF image.",
    };
  }

  return {
    ok: true,
    mimeType,
    extension: PRODUCT_IMAGE_EXTENSIONS[mimeType],
  };
}

/**
 * Where one uploaded image would live: `{productId}/{randomUUID}.{extension}`.
 *
 * The browser-supplied filename is never part of this. Both segments are UUIDs,
 * whose character set makes a traversal segment, an absolute path, or a
 * surprising encoding impossible to express, and the product folder comes from
 * the validated product id — so an upload cannot be aimed at another product's
 * folder even if the request tried.
 *
 * The random name also means object paths cannot be guessed, which is what
 * keeps a public bucket from being enumerable.
 *
 * `createObjectName` exists so tests can pin the random half; it defaults to
 * crypto.randomUUID and its result is validated too, so an unusual generator
 * cannot widen the shape. Returns null for a product id that is not a UUID.
 */
export function buildProductImageObjectPath(
  productId: unknown,
  mimeType: ProductImageMimeType,
  createObjectName: () => string = () => crypto.randomUUID(),
): string | null {
  if (typeof productId !== "string") {
    return null;
  }

  const normalizedProductId = productId.trim().toLowerCase();

  if (!UUID_PATTERN.test(normalizedProductId)) {
    return null;
  }

  const objectName = createObjectName();

  if (typeof objectName !== "string") {
    return null;
  }

  const normalizedObjectName = objectName.trim().toLowerCase();

  if (!UUID_PATTERN.test(normalizedObjectName)) {
    return null;
  }

  return `${normalizedProductId}/${normalizedObjectName}.${PRODUCT_IMAGE_EXTENSIONS[mimeType]}`;
}

/** Whether a stored value is an object path this application generated. */
export function isValidStorageObjectPath(value: unknown): value is string {
  return (
    typeof value === "string" && STORAGE_OBJECT_PATH_PATTERN.test(value)
  );
}

/** The product a stored object belongs to, taken from its own path. */
export function getProductIdFromStorageObjectPath(
  value: unknown,
): string | null {
  if (!isValidStorageObjectPath(value)) {
    return null;
  }

  return value.slice(0, value.indexOf("/"));
}

function getSupabaseOrigin(supabaseUrl: unknown): string | null {
  if (typeof supabaseUrl !== "string" || supabaseUrl.trim() === "") {
    return null;
  }

  try {
    return new URL(supabaseUrl.trim()).origin;
  } catch {
    return null;
  }
}

/**
 * The object path behind a Sombre Storage image URL, or null when the value is
 * not one.
 *
 * Deliberately narrow. The origin must match the configured Supabase project
 * exactly, the path must sit under this bucket's public object endpoint, and
 * what remains must be an object path this application would have generated.
 * Another bucket on the same project, a signed-URL endpoint, the REST API, a
 * query string, or a percent-encoded traversal all fall through to null.
 */
export function getStorageObjectPathFromUrl(
  value: unknown,
  supabaseUrl: unknown,
): string | null {
  const origin = getSupabaseOrigin(supabaseUrl);

  if (!origin || typeof value !== "string") {
    return null;
  }

  let url: URL;

  try {
    url = new URL(value.trim());
  } catch {
    return null;
  }

  if (url.origin !== origin || url.search !== "" || url.hash !== "") {
    return null;
  }

  if (!url.pathname.startsWith(STORAGE_PUBLIC_PREFIX)) {
    return null;
  }

  let objectPath: string;

  try {
    objectPath = decodeURIComponent(
      url.pathname.slice(STORAGE_PUBLIC_PREFIX.length),
    );
  } catch {
    // A malformed escape sequence. Not one of ours.
    return null;
  }

  return isValidStorageObjectPath(objectPath) ? objectPath : null;
}

export function isSombreStorageImageUrl(
  value: unknown,
  supabaseUrl: unknown,
): boolean {
  return getStorageObjectPathFromUrl(value, supabaseUrl) !== null;
}

/**
 * The public URL an object path is served from, or null when either input is
 * not valid. The inverse of `getStorageObjectPathFromUrl`.
 */
export function buildProductImagePublicUrl(
  objectPath: unknown,
  supabaseUrl: unknown,
): string | null {
  const origin = getSupabaseOrigin(supabaseUrl);

  if (!origin || !isValidStorageObjectPath(objectPath)) {
    return null;
  }

  return `${origin}${STORAGE_PUBLIC_PREFIX}${objectPath}`;
}
